var cl_us = [
{"name" : "coral red", "value" : 0xef857d},
{"name" : "poppy red", "value" : 0xea5550},
{"name" : "red", "value" : 0xea5550},
{"name" : "tomato red", "value" : 0xea5549},
{"name" : "vermilion", "value" : 0xea553a},
{"name" : "scarlet", "value" : 0xea5532},
{"name" : "carrot orange", "value" : 0xed6d35},
{"name" : "chinese red", "value" : 0xed6d46},
{"name" : "terracotta", "value" : 0xbd6856},
{"name" : "cocoa brown", "value" : 0x98605e},
{"name" : "mahogany", "value" : 0x6b3f31},
{"name" : "chocolate", "value" : 0x6c3524},
{"name" : "marron", "value" : 0x6a1917},
{"name" : "sepia", "value" : 0x622d18},
{"name" : "coffee", "value" : 0x7b5544},
{"name" : "brown", "value" : 0x8f6552},
{"name" : "burnt sienna", "value" : 0xbb5535},
{"name" : "amber rose", "value" : 0xe6bfb2},
{"name" : "beige rose", "value" : 0xe8d3ca},
{"name" : "salmon pink", "value" : 0xf3a68c},
{"name" : "sahara", "value" : 0xe29676},
{"name" : "ash rose", "value" : 0xe6bfab},
{"name" : "shell pink", "value" : 0xfbdac8},
{"name" : "baby pink", "value" : 0xfdede4},
{"name" : "nail pink", "value" : 0xfce4d6},
{"name" : "raw sienna", "value" : 0xe17b34},
{"name" : "caramel", "value" : 0xbc611e},
{"name" : "sunset", "value" : 0xf6b483},
{"name" : "cinnamon", "value" : 0xbe8f68},
{"name" : "tan", "value" : 0xbf783e},
{"name" : "champagne", "value" : 0xe9dacb},
{"name" : "peach", "value" : 0xfbd8b5},
{"name" : "cafe au lait", "value" : 0x946c45},
{"name" : "orange", "value" : 0xee7800},
{"name" : "apricot", "value" : 0xf7b977},
{"name" : "amber", "value" : 0xc2894b},
{"name" : "bronze", "value" : 0xac6b25},
{"name" : "vanilla", "value" : 0xe8c59c},
{"name" : "cork", "value" : 0xc49a6a},
{"name" : "burnt umber", "value" : 0x6f5436},
{"name" : "raw umber", "value" : 0x866629},
{"name" : "flesh", "value" : 0xfad09e},
{"name" : "golden yellow", "value" : 0xf6ae54},
{"name" : "mandarin orange", "value" : 0xf3981d},
{"name" : "marigold", "value" : 0xf39800},
{"name" : "ecru beige", "value" : 0xf6e5cc},
{"name" : "oyster", "value" : 0xeae1cf},
{"name" : "ochre", "value" : 0xba8b40},
{"name" : "khaki", "value" : 0xc5a05a},
{"name" : "buff", "value" : 0xcaac71},
{"name" : "saffron yellow", "value" : 0xfac559},
{"name" : "pumpkin", "value" : 0xe5a323},
{"name" : "yellow ocher", "value" : 0xc4972f},
{"name" : "blond", "value" : 0xf2d58a},
{"name" : "beige", "value" : 0xeedcb3},
{"name" : "biscuit", "value" : 0xead7a4},
{"name" : "leghorn", "value" : 0xffe9a9},
{"name" : "sunshine yellow", "value" : 0xffedab},
{"name" : "cream yellow", "value" : 0xfff3b8},
{"name" : "naples yellow", "value" : 0xfdd35c},
{"name" : "topaz", "value" : 0xe9bc00},
{"name" : "chrome yellow", "value" : 0xfcc800},
{"name" : "cream", "value" : 0xe3d7a3},
{"name" : "straw", "value" : 0xece093},
{"name" : "jasmine yellow", "value" : 0xedde7b},
{"name" : "antique gold", "value" : 0xc1ab05},
{"name" : "olive", "value" : 0x72640c},
{"name" : "olive drab", "value" : 0x665a1a},
{"name" : "jaune brillant", "value" : 0xffdc00},
{"name" : "yellow", "value" : 0xffdc00},
{"name" : "citrus", "value" : 0xeddc44},
{"name" : "limelight", "value" : 0xfff799},
{"name" : "canary yellow", "value" : 0xfff462},
{"name" : "mimosa", "value" : 0xfff462},
{"name" : "lemon yellow", "value" : 0xfff352},
{"name" : "melon yellow", "value" : 0xe0de94},
{"name" : "chartreuse yellow", "value" : 0xe3e548},
{"name" : "lime yellow", "value" : 0xeaeea2},
{"name" : "lime green", "value" : 0xe6eb94},
{"name" : "chartreuse green", "value" : 0xd9e367},
{"name" : "lettuce green", "value" : 0xd1de4c},
{"name" : "olive green", "value" : 0x5f6527},
{"name" : "moss green", "value" : 0x777e41},
{"name" : "grass green", "value" : 0x7b8d42},
{"name" : "spring green", "value" : 0x9cbb1c},
{"name" : "leaf green", "value" : 0x9fc24d},
{"name" : "white lily", "value" : 0xf0f6da},
{"name" : "asparagus green", "value" : 0xdbebc4},
{"name" : "citron green", "value" : 0x618e34},
{"name" : "meadow green", "value" : 0x65ab31},
{"name" : "apple green", "value" : 0xa7d28d},
{"name" : "ivy green", "value" : 0x578a3d},
{"name" : "spinach green", "value" : 0x417038},
{"name" : "cactus", "value" : 0x387d39},
{"name" : "sky green", "value" : 0xbee0c2},
{"name" : "spearmint", "value" : 0x79c06e},
{"name" : "mint green", "value" : 0x89c997},
{"name" : "parrot green", "value" : 0x37a34a},
{"name" : "summer green", "value" : 0x009944},
{"name" : "opal green", "value" : 0xbee0ce},
{"name" : "spray green", "value" : 0xa4d5bd},
{"name" : "bottle green", "value" : 0x004d25},
{"name" : "cobalt green", "value" : 0x3cb37a},
{"name" : "evergreen", "value" : 0x00984f},
{"name" : "malachite green", "value" : 0x009854},
{"name" : "green", "value" : 0x00a960},
{"name" : "emerald green", "value" : 0x00a968},
{"name" : "forest green", "value" : 0x288c66},
{"name" : "viridian", "value" : 0x00885a},
{"name" : "holly green", "value" : 0x006948},
{"name" : "billiard green", "value" : 0x005c42},
{"name" : "chrome green", "value" : 0x00533f},
{"name" : "antique green", "value" : 0x54917f},
{"name" : "water green", "value" : 0xa5c9c1},
{"name" : "ice green", "value" : 0xa3d6cc},
{"name" : "turquoise green", "value" : 0x00947a},
{"name" : "sea green", "value" : 0x00ac97},
{"name" : "peppermint green", "value" : 0x00ac9a},
{"name" : "peacock green", "value" : 0x00a497},
{"name" : "nile blue", "value" : 0x2cb4ad},
{"name" : "saxe blue", "value" : 0x418b89},
{"name" : "slate green", "value" : 0x3c7170},
{"name" : "teal green", "value" : 0x006a6c},
{"name" : "aqua green", "value" : 0x88bfbf},
{"name" : "aquamarine", "value" : 0x67b5b7},
{"name" : "peacock blue", "value" : 0x009e9f},
{"name" : "turquoise", "value" : 0x009b9f},
{"name" : "capri blue", "value" : 0x00a3a7},
{"name" : "cambridge blue", "value" : 0x25b7c0},
{"name" : "turquoise blue", "value" : 0x00afcc},
{"name" : "horizon blue", "value" : 0x82cddd},
{"name" : "summer shower", "value" : 0xa1d8e2},
{"name" : "horizon blue", "value" : 0xa1d8e6},
{"name" : "cerulean blue", "value" : 0x008db7},
{"name" : "duck blue", "value" : 0x007199},
{"name" : "marine blue", "value" : 0x006888},
{"name" : "madonna blue", "value" : 0x00608d},
{"name" : "egyptian blue", "value" : 0x0073a8},
{"name" : "baby blue", "value" : 0xbbe2f1},
{"name" : "sky blue", "value" : 0xa0d8ef},
{"name" : "shadow blue", "value" : 0x719bad},
{"name" : "cyan", "value" : 0x00a1e9},
{"name" : "yacht blue", "value" : 0x409ecc},
{"name" : "chalk blue", "value" : 0x68a9cf},
{"name" : "pigeon blue", "value" : 0x88b5d3},
{"name" : "smoke blue", "value" : 0xa4c1d7},
{"name" : "frosty blue", "value" : 0xbbdbf3},
{"name" : "bleu acide", "value" : 0x006eb0},
{"name" : "cobalt blue", "value" : 0x0068b7},
{"name" : "sapphire blue", "value" : 0x0068b7},
{"name" : "spectrum blue", "value" : 0x0075c2},
{"name" : "blue", "value" : 0x0075c2},
{"name" : "zenith blue", "value" : 0x4496d3},
{"name" : "heavenly blue", "value" : 0x68a4d9},
{"name" : "orchid gray", "value" : 0xbcc7d7},
{"name" : "powder blue", "value" : 0xbccddb},
{"name" : "light blue", "value" : 0xb2cbe4},
{"name" : "baby blue", "value" : 0xa2c2e6},
{"name" : "day dream", "value" : 0xa3b9e0},
{"name" : "salvia blue", "value" : 0x94adda},
{"name" : "hyacinth blue", "value" : 0x7a99cf},
{"name" : "hyacinth", "value" : 0x6c9bd2},
{"name" : "midnight blue", "value" : 0x001e43},
{"name" : "navy blue", "value" : 0x202f55},
{"name" : "prussian blue", "value" : 0x192f60},
{"name" : "iron blue", "value" : 0x192f60},
{"name" : "indigo", "value" : 0x043c78},
{"name" : "ink blue", "value" : 0x003f8e},
{"name" : "oriental blue", "value" : 0x26499d},
{"name" : "ultramarine blue", "value" : 0x4753a2},
{"name" : "ultramarine", "value" : 0x434da2},
{"name" : "wistaria", "value" : 0x8d93c8},
{"name" : "blue lavender", "value" : 0xa4a8d4},
{"name" : "pannsy", "value" : 0x4d4398},
{"name" : "violet", "value" : 0x5a4498},
{"name" : "heliotrope", "value" : 0x9079b6},
{"name" : "deep royal purple", "value" : 0x47266e},
{"name" : "grape", "value" : 0x56256e},
{"name" : "mauve", "value" : 0x915da3},
{"name" : "iris", "value" : 0xc7a5cc},
{"name" : "lilac", "value" : 0xd1bada},
{"name" : "lavender", "value" : 0xcab8d9},
{"name" : "crocus", "value" : 0xb79fcb},
{"name" : "lavender mauve", "value" : 0xa688bd},
{"name" : "purple", "value" : 0x9b72b0},
{"name" : "royal purple", "value" : 0x7f1184},
{"name" : "raisin", "value" : 0x6b395f},
{"name" : "plum", "value" : 0x6c2463},
{"name" : "raspberry", "value" : 0x841a75},
{"name" : "framboise", "value" : 0x9a0d7c},
{"name" : "dahlia purple", "value" : 0xa50082},
{"name" : "orchid purple", "value" : 0xaf0082},
{"name" : "raspberry red", "value" : 0x9f166a},
{"name" : "orchid", "value" : 0xd9aacd},
{"name" : "lilla", "value" : 0xe0b5d3},
{"name" : "rose tendre", "value" : 0xe6afcf},
{"name" : "orchid pink", "value" : 0xda81b2},
{"name" : "cyclamen pink", "value" : 0xd04f97},
{"name" : "magenta", "value" : 0xe4007f},
{"name" : "bougainvillaea", "value" : 0xe62f8b},
{"name" : "ruby", "value" : 0xc70067},
{"name" : "claret", "value" : 0x941f57},
{"name" : "azalee", "value" : 0xd83473},
{"name" : "cosmos", "value" : 0xdc6b9a},
{"name" : "lotus pink", "value" : 0xde82a7},
{"name" : "old orchid", "value" : 0xe3adc1},
{"name" : "rose mist", "value" : 0xdebecc},
{"name" : "rose dragee", "value" : 0xe5c1cd},
{"name" : "cherry pink", "value" : 0xeb6ea0},
{"name" : "opera", "value" : 0xe95388},
{"name" : "rose red", "value" : 0xea618e},
{"name" : "old lilac", "value" : 0xb0778c},
{"name" : "cocoa", "value" : 0x6e4a55},
{"name" : "wine red", "value" : 0xb33e5c},
{"name" : "garnet", "value" : 0x942343},
{"name" : "cochineal red", "value" : 0xc82c55},
{"name" : "strawberry", "value" : 0xe73562},
{"name" : "ruby red", "value" : 0xe73562},
{"name" : "carmine", "value" : 0xd70035},
{"name" : "signal red", "value" : 0xe8383d},
{"name" : "burgundy", "value" : 0x6c2735},
{"name" : "bordeaux", "value" : 0x6c272d},
{"name" : "camellia", "value" : 0xda536e},
{"name" : "rose", "value" : 0xe95464},
{"name" : "rose pink", "value" : 0xf19ca7},
{"name" : "pink", "value" : 0xf5b2b2},
{"name" : "flamingo pink", "value" : 0xf5b2ac},
{"name" : "old rose", "value" : 0xe29399},
{"name" : "pink almond", "value" : 0xe3acae},
{"name" : "rose dust", "value" : 0xe6c0c0},
{"name" : "white", "value" : 0xffffff},
{"name" : "snow white", "value" : 0xfafdff},
{"name" : "pink white", "value" : 0xfef9fb},
{"name" : "milky white", "value" : 0xfffff9},
{"name" : "amber white", "value" : 0xfff9f5},
{"name" : "lavender ice", "value" : 0xf7f6fb},
{"name" : "pearl white", "value" : 0xf7f6f5},
{"name" : "ivory", "value" : 0xf8f4e6},
{"name" : "powder pink", "value" : 0xf5ecf4},
{"name" : "silver white", "value" : 0xefefef},
{"name" : "frosty gray", "value" : 0xe8ece9},
{"name" : "silver pink", "value" : 0xeeeaec},
{"name" : "beige cameo", "value" : 0xeee9e6},
{"name" : "ecru", "value" : 0xeee7e0},
{"name" : "pink beige", "value" : 0xede4e1},
{"name" : "frosty white", "value" : 0xe6eae6},
{"name" : "oyster white", "value" : 0xeae8e1},
{"name" : "wisteria mist", "value" : 0xd3d6dd},
{"name" : "cloud", "value" : 0xd4d9df},
{"name" : "moon gray", "value" : 0xd4d9dc},
{"name" : "china clay", "value" : 0xd4dcd3},
{"name" : "sand beige", "value" : 0xdcd6d2},
{"name" : "orchid mist", "value" : 0xd3d3d8},
{"name" : "reed gray", "value" : 0xd4d9d6},
{"name" : "sky gray", "value" : 0xcbd0d3},
{"name" : "lavender gray", "value" : 0xbcbace},
{"name" : "silver", "value" : 0xc9caca},
{"name" : "pearl gray", "value" : 0xc9c9c4},
{"name" : "sand gray", "value" : 0xc9c9c2},
{"name" : "marble gray", "value" : 0xc0c5c2},
{"name" : "opal gray", "value" : 0xbfbec5},
{"name" : "french gray", "value" : 0x8da0b6},
{"name" : "mist", "value" : 0xb4aeb1},
{"name" : "ash blond", "value" : 0xb5b5ae},
{"name" : "fog", "value" : 0xabb1b5},
{"name" : "beige gray", "value" : 0xb4ada9},
{"name" : "silver gray", "value" : 0xafafb0},
{"name" : "storm gray", "value" : 0xaaaab0},
{"name" : "green fog", "value" : 0xabb1ad},
{"name" : "ash gray", "value" : 0x9fa09e},
{"name" : "rose gray", "value" : 0x9d8e87},
{"name" : "elephant skin", "value" : 0x9f9f98},
{"name" : "battleship gray", "value" : 0x898989},
{"name" : "stone gray", "value" : 0x898880},
{"name" : "moss gray", "value" : 0x7e837f},
{"name" : "dove gray", "value" : 0x7d7b83},
{"name" : "gray", "value" : 0x7d7d7d},
{"name" : "steel gray", "value" : 0x736d71},
{"name" : "ivy gray", "value" : 0x666c67},
{"name" : "slate gray", "value" : 0x626063},
{"name" : "graphite", "value" : 0x594e52},
{"name" : "charcoal gray", "value" : 0x4e454a},
{"name" : "taupe", "value" : 0x504946},
{"name" : "lamp black", "value" : 0x24140e},
{"name" : "black", "value" : 0x000000}
];